Repository Team-Ampersand/GUS, pull requests merged in 2023-08, with the labels that each got.

#20 🔀 :: (#19) 디자인 시스템 Court 구현
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/court/GYMIBadmintonCourt.kt
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/court/GYMIBasketballCourt.kt
  GYMI-components/src/main/res/drawable/ic_badminton_court.xml
  GYMI-components/src/main/res/drawable/ic_basketball_court.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#22 🔀 :: (#21) 디자인 시스템 NoticeItem 구현
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/item/GYMINoticeItem.kt
  GYMI-components/src/main/java/com/mpersand/gymi_components/theme/GYMITypography.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#25 🔀 :: (#24) design system card
  GYMI-components/build.gradle.kts
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/card/GYMICard.kt
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#27 🔀 :: (#26) design system textfield
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/textfield/GYMITextField.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#28 🔀 :: (#23) 디자인 시스템 Snackbar 구현
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/snackbar/GYMISnackbar.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#30 🔀 (#29) releases for 1.0.0
  GYMI-components/build.gradle.kts
  app/build.gradle.kts
  build.gradle.kts
Labels: 0️⃣ Priority: Critical, 🎨 Type: Publishing

#34 🔀 :: (#33) fix jitpack issue
  GYMI-components/build.gradle.kts
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#39 🔀 :: (#37) GYMICourt contentScale 변경
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/court/GYMIBadmintonCourt.kt
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/court/GYMIBasketballCourt.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#40 🔀 :: (#38) GYMINavBar backgroundColor 디폴트 값 변경
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/navbar/GYMINavBar.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#42 🔀 :: (#41) add content padding for button
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/button/GYMIButton.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#44 🔀 :: (#43) fix textfield
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/textfield/GYMITextField.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#46 🔀 :: (#45) 컬러 시스템 Black&White 색상 추가
  GYMI-components/src/main/java/com/mpersand/gymi_components/theme/GYMIColor.kt
  GYMI-components/src/main/java/com/mpersand/gymi_components/theme/GYMITheme.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#48 🔀 :: (#47) modify badminton court component
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/court/GYMIBadmintonCourt.kt
  GYMI-components/src/main/res/drawable/ic_badminton_court.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#50 🔀 :: (#49) gymi notice item dark theme setting
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/item/GYMINoticeItem.kt
  GYMI-components/src/main/java/com/mpersand/gymi_components/theme/GYMITheme.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#52 🔀 :: (#51) refactoring text field
  GYMI-components/src/main/java/com/mpersand/gymi_components/component/textfield/GYMITextField.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector
